### ISSUE TITLE
Possible improvement for method 'factors'

### ISSUE THREAD

**Issue by OshinoMoumou** [Erotemic/utool#11]
Greetings!
I noticed that method factors referred a StackOverflow post, while [a recent comment](https://stackoverflow.com/questions/6800193/what-is-the-most-efficient-way-of-finding-all-the-factors-of-a-number-in-python#comment95557261_6800214) to it mentioned that using 'if not n % i' instead of 'if n % i == 0' can speed up for 20-30%.
I'm trying to learn the usefulness of such small updates on StackOverflow. Would this comment help improve your code? I understand that such speedup might not be that helpful in real life situation. In that case, do you think this comment can help promote future projects (for example, when the code were reused somewhere else)? 
I'll really appreciate it if you could kindly give me some feedback or suggestions. Thank you very much for your time.
Have a nice day!

**Comment by Erotemic** [comment]
This project isn't in active development, and only exists for legacy reasons, so I'd rather not make any changes that aren't maintenance patches.
